"""Unit tests for record shaping and redaction.

Redaction is the privacy boundary, so these tests assert not just that permitted
content is present but that forbidden content is absent.
"""

import pytest

from edge_ai_monitor.export.records import (
    DEFAULT_LEVEL,
    LEVEL_ANALYSIS,
    LEVEL_FULL,
    LEVEL_METADATA,
    build_record,
    effective_level,
    severity_at_least,
)

PROPOSAL = {
    "error_summary": "Database connection refused",
    "root_cause": "The postgres container is not listening",
    "severity": "high",
    "remediation_steps": ["Step 1: Check the container", "Step 2: Restart it"],
    "confidence": 0.9,
    "requires_human_review": True,
    "metadata": {
        "problem_key": "abc123def456",
        "workload_id": "examples/sensor_1.2.0_amd64",
        "service_name": "sensor",
        "service_version": "1.2.0",
        "organization": "examples",
        "first_seen": "2026-08-14T10:00:00+00:00",
        "last_seen": "2026-08-14T12:00:00+00:00",
        "total_occurrences": 42,
        "analysis_count": 2,
        "matched_pattern": "ERROR",
        "log_path": "/var/log/workloads/sensor/app.log",
        "line_number": 88,
        "log_context": "INFO starting\nERROR could not connect\nINFO retrying",
    },
}

# Content that must never appear below its permitted level.
ANALYSIS_CONTENT = ["Database connection refused", "postgres container", "Restart it"]
FULL_CONTENT = ["/var/log/workloads/sensor/app.log", "could not connect", "INFO retrying"]


def payload_text(record):
    import json

    return json.dumps(record.payload)


# ---------------- metadata level ----------------


def test_metadata_is_the_default_level():
    record = build_record(PROPOSAL)
    assert record.level == DEFAULT_LEVEL == LEVEL_METADATA


def test_metadata_level_includes_identity_and_counts():
    record = build_record(PROPOSAL, level=LEVEL_METADATA)
    assert record.payload["service_name"] == "sensor"
    assert record.payload["severity"] == "high"
    assert record.payload["total_occurrences"] == 42
    assert record.payload["first_seen"] == "2026-08-14T10:00:00+00:00"


def test_metadata_level_leaks_no_analysis():
    text = payload_text(build_record(PROPOSAL, level=LEVEL_METADATA))
    for fragment in ANALYSIS_CONTENT:
        assert fragment not in text


def test_metadata_level_leaks_no_log_content():
    text = payload_text(build_record(PROPOSAL, level=LEVEL_METADATA))
    for fragment in FULL_CONTENT:
        assert fragment not in text


# ---------------- analysis level ----------------


def test_analysis_level_adds_the_model_conclusions():
    record = build_record(PROPOSAL, level=LEVEL_ANALYSIS)
    assert record.payload["error_summary"] == "Database connection refused"
    assert record.payload["root_cause"].startswith("The postgres")
    assert len(record.payload["remediation_steps"]) == 2


def test_analysis_level_carries_the_ai_disclaimer():
    record = build_record(PROPOSAL, level=LEVEL_ANALYSIS)
    assert "generated by an AI system" in record.payload["disclaimer"]


def test_analysis_level_still_withholds_log_content():
    text = payload_text(build_record(PROPOSAL, level=LEVEL_ANALYSIS))
    assert "INFO retrying" not in text
    assert "/var/log/workloads/sensor/app.log" not in text


# ---------------- full level ----------------


def test_full_level_includes_everything():
    record = build_record(PROPOSAL, level=LEVEL_FULL)
    assert record.payload["log_path"] == "/var/log/workloads/sensor/app.log"
    assert record.payload["line_number"] == 88
    assert "could not connect" in record.payload["log_context"]
    assert record.payload["root_cause"]


# ---------------- node identity ----------------


def test_node_identity_included_when_supplied():
    record = build_record(PROPOSAL, node={"id": "myorg/edge-1"})
    assert record.payload["node"]["id"] == "myorg/edge-1"


def test_node_identity_omitted_when_not_supplied():
    assert "node" not in build_record(PROPOSAL).payload


# ---------------- unknown level ----------------


def test_unknown_level_falls_back_to_metadata():
    record = build_record(PROPOSAL, level="everything-please")
    assert record.level == LEVEL_METADATA
    assert "root_cause" not in record.payload


# ---------------- consent clamping ----------------


@pytest.mark.parametrize("level", [LEVEL_ANALYSIS, LEVEL_FULL])
def test_content_levels_clamped_without_workload_consent(level):
    assert effective_level(level, workload_permits_content=False) == LEVEL_METADATA


@pytest.mark.parametrize("level", [LEVEL_ANALYSIS, LEVEL_FULL])
def test_content_levels_allowed_with_consent(level):
    assert effective_level(level, workload_permits_content=True) == level


def test_metadata_level_needs_no_consent():
    assert effective_level(LEVEL_METADATA, workload_permits_content=False) == LEVEL_METADATA


# ---------------- idempotency ----------------


def test_idempotency_key_is_stable_for_the_same_state():
    assert build_record(PROPOSAL).idempotency_key == build_record(PROPOSAL).idempotency_key


def test_idempotency_key_changes_with_new_occurrences():
    import copy

    later = copy.deepcopy(PROPOSAL)
    later["metadata"]["total_occurrences"] = 43
    assert build_record(PROPOSAL).idempotency_key != build_record(later).idempotency_key


def test_idempotency_key_differs_across_problems():
    import copy

    other = copy.deepcopy(PROPOSAL)
    other["metadata"]["problem_key"] = "different"
    assert build_record(PROPOSAL).idempotency_key != build_record(other).idempotency_key


# ---------------- severity threshold ----------------


@pytest.mark.parametrize(
    "severity,threshold,expected",
    [
        ("critical", "high", True),
        ("high", "high", True),
        ("medium", "high", False),
        ("low", "high", False),
        ("low", "all", True),
        ("medium", "medium", True),
    ],
)
def test_severity_threshold(severity, threshold, expected):
    assert severity_at_least(severity, threshold) is expected
