"""Generation and persistence of remediation proposals."""

import json
import logging
import os
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from .error_analyzer import AnalysisResult

logger = logging.getLogger(__name__)

DEFAULT_PROPOSAL_DIR = "/var/lib/monitor/proposals"

DISCLAIMER = (
    "This remediation proposal is generated by an AI system. Validate all steps "
    "before execution in production environments."
)

# Thresholds from the remediation-proposals spec.
HUMAN_REVIEW_CONFIDENCE = 0.6
LOW_CONFIDENCE = 0.5
ROUTINE_CONFIDENCE = 0.8
ROUTINE_SEVERITIES = ("low", "medium")

DIAGNOSTIC_STEPS = [
    "Collect the full log file surrounding the reported line for additional context.",
    "Check the service status with `hzn service list` and review recent agreement events.",
    "Inspect container logs with `docker logs <container>` for the affected workload.",
    "Verify the workload's configuration and environment variables against its service definition.",
]


def _utcnow() -> str:
    return datetime.now(timezone.utc).isoformat()


def _safe_dirname(value: str) -> str:
    """Make a workload id safe to use as a single path segment."""
    return re.sub(r"[^A-Za-z0-9._-]", "_", value) or "unknown"


@dataclass
class Proposal:
    """A structured, reviewable remediation proposal."""

    error_summary: str
    root_cause: str
    severity: str
    remediation_steps: List[str]
    confidence: float
    requires_human_review: bool
    disclaimer: str = DISCLAIMER
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "error_summary": self.error_summary,
            "root_cause": self.root_cause,
            "severity": self.severity,
            "remediation_steps": list(self.remediation_steps),
            "confidence": self.confidence,
            "requires_human_review": self.requires_human_review,
            "disclaimer": self.disclaimer,
            "metadata": dict(self.metadata),
        }

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent, sort_keys=True)


def requires_human_review(severity: str, confidence: float) -> bool:
    """Decide whether a proposal must be reviewed before acting on it.

    Critical severity or low confidence always requires review; routine
    proposals are low/medium severity with high confidence.
    """
    if severity == "critical" or confidence < HUMAN_REVIEW_CONFIDENCE:
        return True
    if severity in ROUTINE_SEVERITIES and confidence >= ROUTINE_CONFIDENCE:
        return False
    # Everything in between (e.g. high severity, or medium confidence) is
    # flagged so an operator takes a look.
    return True


class RemediationGenerator:
    """Turns analysis results into proposals and writes them to disk."""

    def __init__(self, proposal_dir: str = DEFAULT_PROPOSAL_DIR):
        self.proposal_dir = Path(proposal_dir)
        self.written_count = 0
        self.storage_failures = 0

    # ---------------- generation ----------------

    def generate(self, result: AnalysisResult) -> Proposal:
        """Build a proposal from an analysis result."""
        steps = list(result.remediation_steps)

        # Without confident context, hand back diagnostics rather than guesses.
        if result.confidence < LOW_CONFIDENCE or not steps:
            steps = self._with_diagnostics(steps, result)

        steps = self._tailor_to_workload(steps, result)

        return Proposal(
            error_summary=result.error_summary,
            root_cause=result.root_cause,
            severity=result.severity,
            remediation_steps=steps,
            confidence=result.confidence,
            requires_human_review=requires_human_review(result.severity, result.confidence),
            metadata=self._build_metadata(result),
        )

    @staticmethod
    def _with_diagnostics(steps: List[str], result: AnalysisResult) -> List[str]:
        """Append diagnostic steps when the analysis was inconclusive."""
        logger.info(
            "analysis confidence %.2f is low; adding diagnostic steps for %s",
            result.confidence,
            result.event.log_path,
        )
        combined = list(steps)
        for step in DIAGNOSTIC_STEPS:
            if step not in combined:
                combined.append(step)
        return combined

    @staticmethod
    def _tailor_to_workload(steps: List[str], result: AnalysisResult) -> List[str]:
        """Number the steps and anchor them to this workload's identity."""
        service = result.workload_metadata.get("service_name", "the workload")
        org = result.workload_metadata.get("organization")
        version = result.workload_metadata.get("version")

        numbered = [f"Step {i}: {step}" for i, step in enumerate(steps, start=1)]

        identity = service if not version else f"{service} v{version}"
        if org:
            identity = f"{org}/{identity}"
        numbered.append(
            f"Step {len(numbered) + 1}: Verify {identity} recovered by re-checking "
            f"{result.event.log_path} for further occurrences."
        )
        return numbered

    def _build_metadata(self, result: AnalysisResult) -> Dict[str, Any]:
        event = result.event
        return {
            "timestamp": _utcnow(),
            "detected_at": event.timestamp,
            "workload_id": event.workload_id,
            "service_name": result.workload_metadata.get("service_name"),
            "service_version": result.workload_metadata.get("version"),
            "organization": result.workload_metadata.get("organization"),
            "log_path": event.log_path,
            "line_number": event.line_number,
            "matched_pattern": event.matched_pattern,
            "occurrences": result.occurrences,
            "analysis_duration_ms": result.analysis_duration_ms,
        }

    # ---------------- persistence ----------------

    def proposal_path(self, proposal: Proposal) -> Path:
        """Destination path: <dir>/<workload>/<timestamp>.json."""
        workload = _safe_dirname(str(proposal.metadata.get("workload_id", "unknown")))
        stamp = _safe_dirname(str(proposal.metadata.get("timestamp", _utcnow())))
        return self.proposal_dir / workload / f"{stamp}.json"

    def persist(self, proposal: Proposal) -> Optional[Path]:
        """Write a proposal to disk, falling back to stdout logging on failure."""
        path = self.proposal_path(proposal)
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            # Write to a temp file then rename so readers never see a partial file.
            tmp = path.with_suffix(".json.tmp")
            tmp.write_text(proposal.to_json(), encoding="utf-8")
            os.replace(tmp, path)
        except OSError as exc:
            self.storage_failures += 1
            logger.error(
                "could not write proposal to %s: %s; emitting to stdout instead", path, exc
            )
            # The proposal must not be lost just because storage is unavailable.
            print(proposal.to_json(), flush=True)
            return None

        self.written_count += 1
        logger.info(
            "wrote %s severity proposal for %s to %s",
            proposal.severity,
            proposal.metadata.get("workload_id"),
            path,
        )
        return path

    def handle_result(self, result: AnalysisResult) -> Proposal:
        """Generate and persist a proposal for one analysis result."""
        proposal = self.generate(result)
        self.persist(proposal)
        return proposal
