"""Shaping proposals into exportable records, with redaction.

Redaction is the privacy boundary. The service's standing guarantee is that log
content never leaves the node; export breaks that deliberately and selectively,
so what each level transmits is defined here in one place and nowhere else.
"""

import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)

# Ordered least to most revealing. A sink is configured with one of these.
LEVEL_METADATA = "metadata"
LEVEL_ANALYSIS = "analysis"
LEVEL_FULL = "full"

REDACTION_LEVELS = (LEVEL_METADATA, LEVEL_ANALYSIS, LEVEL_FULL)
DEFAULT_LEVEL = LEVEL_METADATA

# Levels at or above this carry content derived from the workload's logs, so a
# workload must opt in before they are used for it.
CONSENT_REQUIRED_LEVELS = (LEVEL_ANALYSIS, LEVEL_FULL)

SEVERITY_ORDER = {"low": 0, "medium": 1, "high": 2, "critical": 3}

AI_DISCLAIMER = (
    "This analysis was generated by an AI system. Validate all steps before "
    "execution in production environments."
)


def _utcnow() -> str:
    return datetime.now(timezone.utc).isoformat()


def level_rank(level: str) -> int:
    """Position of a redaction level, for comparisons."""
    try:
        return REDACTION_LEVELS.index(level)
    except ValueError:
        return 0


def severity_at_least(severity: str, threshold: str) -> bool:
    """True when ``severity`` meets or exceeds ``threshold``."""
    if threshold == "all":
        return True
    return SEVERITY_ORDER.get(severity, 0) >= SEVERITY_ORDER.get(threshold, 99)


@dataclass
class ExportRecord:
    """One problem, shaped for transmission at a given redaction level."""

    problem_key: str
    workload_id: str
    severity: str
    level: str
    payload: Dict[str, Any] = field(default_factory=dict)
    created_at: str = field(default_factory=_utcnow)

    @property
    def idempotency_key(self) -> str:
        """Stable across retries of the same record, distinct across problems.

        Keyed on the problem plus its occurrence tally, so a retry repeats the
        key while a genuinely new occurrence produces a new one.
        """
        occurrences = self.payload.get("total_occurrences", 0)
        return f"{self.problem_key}-{occurrences}"


def _metadata_payload(proposal: Dict[str, Any], node: Optional[Dict[str, str]]) -> Dict[str, Any]:
    """The least revealing view: identity, severity, and counts. No log content.

    Everything here is an operational fact the node operator already holds; none
    of it is derived from the text of the workload's logs.
    """
    metadata = proposal.get("metadata", {})
    payload = {
        "problem_key": metadata.get("problem_key"),
        "workload_id": metadata.get("workload_id"),
        "service_name": metadata.get("service_name"),
        "service_version": metadata.get("service_version"),
        "organization": metadata.get("organization"),
        "severity": proposal.get("severity"),
        "confidence": proposal.get("confidence"),
        "requires_human_review": proposal.get("requires_human_review"),
        "first_seen": metadata.get("first_seen"),
        "last_seen": metadata.get("last_seen"),
        "total_occurrences": metadata.get("total_occurrences"),
        "analysis_count": metadata.get("analysis_count"),
        "matched_pattern": metadata.get("matched_pattern"),
    }
    if node:
        payload["node"] = dict(node)
    return payload


def _analysis_fields(proposal: Dict[str, Any]) -> Dict[str, Any]:
    """The model's conclusions. Derived from log content, so consent-gated."""
    return {
        "error_summary": proposal.get("error_summary"),
        "root_cause": proposal.get("root_cause"),
        "remediation_steps": list(proposal.get("remediation_steps") or []),
        "disclaimer": AI_DISCLAIMER,
    }


def _full_fields(proposal: Dict[str, Any]) -> Dict[str, Any]:
    """The raw evidence: where it happened and the log window around it."""
    metadata = proposal.get("metadata", {})
    return {
        "log_path": metadata.get("log_path"),
        "line_number": metadata.get("line_number"),
        "log_context": metadata.get("log_context"),
    }


def build_record(
    proposal: Dict[str, Any],
    level: str = DEFAULT_LEVEL,
    node: Optional[Dict[str, str]] = None,
) -> ExportRecord:
    """Shape a proposal into a record carrying only what ``level`` permits.

    Fields are added by level rather than removed, so a new proposal field is
    never leaked by omission — it has to be named here to be transmitted.
    """
    if level not in REDACTION_LEVELS:
        logger.warning("unknown redaction level %r; falling back to %s", level, DEFAULT_LEVEL)
        level = DEFAULT_LEVEL

    payload = _metadata_payload(proposal, node)
    if level_rank(level) >= level_rank(LEVEL_ANALYSIS):
        payload.update(_analysis_fields(proposal))
    if level_rank(level) >= level_rank(LEVEL_FULL):
        payload.update(_full_fields(proposal))

    metadata = proposal.get("metadata", {})
    return ExportRecord(
        problem_key=str(metadata.get("problem_key", "unknown")),
        workload_id=str(metadata.get("workload_id", "unknown")),
        severity=str(proposal.get("severity", "medium")),
        level=level,
        payload=payload,
    )


def effective_level(requested: str, workload_permits_content: bool) -> str:
    """Clamp a sink's level to what the workload has consented to.

    A workload opting into local monitoring has not thereby agreed to have its
    log-derived content sent off the node, so anything above metadata requires
    an explicit opt-in.
    """
    if requested in CONSENT_REQUIRED_LEVELS and not workload_permits_content:
        logger.debug(
            "clamping export level %s to %s: workload has not opted into content export",
            requested,
            LEVEL_METADATA,
        )
        return LEVEL_METADATA
    return requested
